# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         List-Group
version:      1.3
version_from: lib/List/Group.pm
installdirs:  site
requires:
    POSIX:                         
    Storable:                      
    Test::Deep:                    
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
